name: streamlit_app
channels:
  - defaults
dependencies:
  - attrs=21.2.0
  - aws-c-common=0.4.57
  - aws-c-event-stream=0.1.6
  - aws-checksums=0.1.9
  - aws-sdk-cpp=1.8.185
  - blas=1.0
  - bottleneck=1.3.2
  - brotli=1.0.9
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2021.7.5
  - cairo=1.16.0
  - certifi=2021.5.30
  - cfitsio=3.470
  - click=7.1.2
  - click-plugins=1.1.1
  - cligj=0.7.2
  - curl=7.78.0
  - cycler=0.10.0
  - expat=2.4.1
  - fiona=1.8.13.post1
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - freetype=2.10.4
  - freexl=1.0.6
  - gdal=3.0.2
  - geopandas=0.9.0
  - geopandas-base=0.9.0
  - geos=3.8.0
  - geotiff=1.6.0
  - gettext=0.21.0
  - giflib=5.2.1
  - glib=2.69.1
  - hdf4=4.2.13
  - hdf5=1.10.6
  - icu=58.2
  - intel-openmp=2021.3.0
  - joblib=1.0.1
  - jpeg=9b
  - json-c=0.13.1
  - kealib=1.4.14
  - kiwisolver=1.3.1
  - krb5=1.19.2
  - lcms2=2.12
  - libboost=1.73.0
  - libcurl=7.78.0
  # - libcxx=10.0.0
  - libdap4=3.19.1
  - libedit=3.1.20210216
  - libev=4.33
  - libffi=3.3
  - libgdal=3.0.2
  # - libgfortran=3.0.1
  # - libiconv=1.16
  - libkml=1.3.0
  - libnetcdf=4.6.1
  - libnghttp2=1.41.0
  - libpng=1.6.37
  - libpq=12.2
  - libspatialindex=1.9.3
  - libspatialite=4.3.0a
  - libssh2=1.9.0
  - libtiff=4.2.0
  - libwebp-base=1.2.0
  - libxml2=2.9.12
  # - llvm-openmp=10.0.0
  - lz4-c=1.9.3
  - mapclassify=2.4.3
  - matplotlib-base=3.4.2
  - mkl=2021.3.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.2
  - munch=2.5.0
  - munkres=1.1.4
  - ncurses=6.2
  - networkx=2.6.2
  - numexpr=2.7.3
  - numpy-base=1.20.3
  - olefile=0.46
  - openjpeg=2.3.0
  - openssl=1.1.1k
  - pcre=8.45
  - pillow=8.3.1
  - pip=21.0.1
  - pixman=0.40.0
  - poppler=0.81.0
  - poppler-data=0.4.10
  - postgresql=12.2
  - proj=6.2.1
  - pyparsing=2.4.7
  - pyproj=2.6.1.post1
  - python=3.7.11
  - python-dateutil=2.8.2
  - pytz=2021.1
  - readline=8.1
  - rtree=0.9.7
  - scikit-learn=0.24.2
  - scipy=1.6.2
  - setuptools=52.0.0
  - shapely=1.7.1
  - six=1.16.0
  - sqlite=3.36.0
  - threadpoolctl=2.2.0
  - tiledb=2.2.9
  - tk=8.6.10
  - tornado=6.1
  - wheel=0.37.0
  - xerces-c=3.2.3
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - altair==4.1.0
    - appnope==0.1.2
    - argcomplete==1.12.3
    - argon2-cffi==20.1.0
    - astor==0.8.1
    - backcall==0.2.0
    - backports-zoneinfo==0.2.1
    - base58==2.1.0
    - bleach==4.0.0
    - blinker==1.4
    - branca==0.4.2
    - cachetools==4.2.2
    - cffi==1.14.6
    - charset-normalizer==2.0.4
    - debugpy==1.4.1
    - decorator==5.0.9
    - defusedxml==0.7.1
    - entrypoints==0.3
    - folium==0.12.1
    - gitdb==4.0.7
    - gitpython==3.1.18
    - idna==3.2
    - importlib-metadata==4.6.4
    - ipykernel==6.2.0
    - ipython==7.26.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.3
    - jedi==0.18.0
    - jinja2==3.0.1
    - jsonschema==3.2.0
    - jupyter-client==7.0.1
    - jupyter-core==4.7.1
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.0.0
    - markupsafe==2.0.1
    - matplotlib-inline==0.1.2
    - mistune==0.8.4
    - nbclient==0.5.4
    - nbconvert==6.1.0
    - nbformat==5.1.3
    - nest-asyncio==1.5.1
    - notebook==6.4.3
    - numpy==1.21.2
    - packaging==21.0
    - pandas==1.3.2
    - pandocfilters==1.4.3
    - parso==0.8.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - prometheus-client==0.11.0
    - prompt-toolkit==3.0.20
    - protobuf==3.17.3
    - ptyprocess==0.7.0
    - pyarrow==5.0.0
    - pycparser==2.20
    - pydeck==0.6.2
    - pygments==2.10.0
    - pyrsistent==0.18.0
    - pyzmq==22.2.1
    - requests==2.26.0
    - send2trash==1.8.0
    - smmap==4.0.0
    - streamlit==0.87.0
    - streamlit-folium==0.4.0
    - terminado==0.11.1
    - testpath==0.5.0
    - toml==0.10.2
    - toolz==0.11.1
    - traitlets==5.0.5
    - typing-extensions==3.10.0.0
    - tzlocal==3.0
    - urllib3==1.26.6
    - validators==0.18.2
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - widgetsnbextension==3.5.1
    - zipp==3.5.0
